"""Localized agent theses for the analytics desk."""

from __future__ import annotations

from typing import Any

SUPPORTED = ("ar", "en", "fr", "zh", "ja", "es", "de", "ko", "ru")

_WORDS: dict[str, dict[str, str]] = {
    "ar": {
        "bullish": "صاعد",
        "bearish": "هابط",
        "neutral": "محايد",
        "bull": "صاعد",
        "bear": "هابط",
        "bullish_engulfing": "ابتلاع صاعد",
        "bearish_engulfing": "ابتلاع هابط",
        "hammer": "مطرقة",
        "shooting_star": "نجم ساقط",
        "none": "لا نمط كلاسيكي",
        "volume_spike": "ارتفاع حجم",
        "rsi_overbought": "تشبع شرائي",
        "rsi_oversold": "تشبع بيعي",
    },
    "en": {
        "bullish": "bullish",
        "bearish": "bearish",
        "neutral": "neutral",
        "bull": "bullish",
        "bear": "bearish",
        "bullish_engulfing": "bullish engulfing",
        "bearish_engulfing": "bearish engulfing",
        "hammer": "hammer",
        "shooting_star": "shooting star",
        "none": "no classical reversal",
        "volume_spike": "volume spike",
        "rsi_overbought": "RSI overbought",
        "rsi_oversold": "RSI oversold",
    },
    "fr": {
        "bullish": "haussier",
        "bearish": "baissier",
        "neutral": "neutre",
        "bull": "haussier",
        "bear": "baissier",
        "bullish_engulfing": "avalement haussier",
        "bearish_engulfing": "avalement baissier",
        "hammer": "marteau",
        "shooting_star": "étoile filante",
        "none": "pas de retournement classique",
        "volume_spike": "pic de volume",
        "rsi_overbought": "RSI suracheté",
        "rsi_oversold": "RSI survendu",
    },
    "zh": {
        "bullish": "看涨",
        "bearish": "看跌",
        "neutral": "中性",
        "bull": "看涨",
        "bear": "看跌",
        "bullish_engulfing": "看涨吞没",
        "bearish_engulfing": "看跌吞没",
        "hammer": "锤头",
        "shooting_star": "流星",
        "none": "无明显反转形态",
        "volume_spike": "放量",
        "rsi_overbought": "RSI超买",
        "rsi_oversold": "RSI超卖",
    },
    "ja": {
        "bullish": "強気",
        "bearish": "弱気",
        "neutral": "中立",
        "bull": "強気",
        "bear": "弱気",
        "bullish_engulfing": "強気の包み線",
        "bearish_engulfing": "弱気の包み線",
        "hammer": "ハンマー",
        "shooting_star": "流れ星",
        "none": "典型的な反転なし",
        "volume_spike": "出来高急増",
        "rsi_overbought": "RSI買われすぎ",
        "rsi_oversold": "RSI売られすぎ",
    },
    "es": {
        "bullish": "alcista",
        "bearish": "bajista",
        "neutral": "neutral",
        "bull": "alcista",
        "bear": "bajista",
        "bullish_engulfing": "envolvente alcista",
        "bearish_engulfing": "envolvente bajista",
        "hammer": "martillo",
        "shooting_star": "estrella fugaz",
        "none": "sin reversión clásica",
        "volume_spike": "pico de volumen",
        "rsi_overbought": "RSI sobrecomprado",
        "rsi_oversold": "RSI sobrevendido",
    },
    "de": {
        "bullish": "bullisch",
        "bearish": "bärisch",
        "neutral": "neutral",
        "bull": "bullisch",
        "bear": "bärisch",
        "bullish_engulfing": "bullische Umfassung",
        "bearish_engulfing": "bärische Umfassung",
        "hammer": "Hammer",
        "shooting_star": "Sternschnuppe",
        "none": "keine klassische Umkehr",
        "volume_spike": "Volumenspitze",
        "rsi_overbought": "RSI überkauft",
        "rsi_oversold": "RSI überverkauft",
    },
    "ko": {
        "bullish": "상승",
        "bearish": "하락",
        "neutral": "중립",
        "bull": "상승",
        "bear": "하락",
        "bullish_engulfing": "상승 장악형",
        "bearish_engulfing": "하락 장악형",
        "hammer": "망치형",
        "shooting_star": "유성형",
        "none": "고전 반전 없음",
        "volume_spike": "거래량 급증",
        "rsi_overbought": "RSI 과매수",
        "rsi_oversold": "RSI 과매도",
    },
    "ru": {
        "bullish": "бычий",
        "bearish": "медвежий",
        "neutral": "нейтральный",
        "bull": "бычий",
        "bear": "медвежий",
        "bullish_engulfing": "бычье поглощение",
        "bearish_engulfing": "медвежье поглощение",
        "hammer": "молот",
        "shooting_star": "падающая звезда",
        "none": "нет классического разворота",
        "volume_spike": "всплеск объёма",
        "rsi_overbought": "RSI перекуплен",
        "rsi_oversold": "RSI перепродан",
    },
}

_TEMPLATES: dict[str, dict[str, str]] = {
    "ar": {
        "liq_bid": "سيولة الشراء والدعم الظاهر يسيطران على دفتر الأوامر.",
        "liq_ask": "جدار البيع والمقاومة يمتصّان الطلب.",
        "liq_flat": "الدفتر متوازن ولا توجد أفضلية سيولة واضحة.",
        "pattern_read": "قراءة الهيكل: {pattern}؛ ميل آخر 30 شمعة = {slope}.",
        "quant_read": "متوسطا 12/26 {ema}، هيستوغرام MACD {hist}، RSI {rsi}، ATR {atr}.",
        "radar_quiet": "لا شذوذ مقابل متوسط آخر 20 شمعة.",
        "radar_alerts": "تنبيهات: {alerts}.",
        "news_empty": "لا عناوين صالحة في ذاكرة الأخبار.",
        "news_tilt": "ميل العناوين {score} عبر {hits} خبر.",
        "risk_vol": "فيتو تقلب: ATR {atr} / مدى الشمعة {range}.",
        "risk_dead": "فيتو النطاق الميت: ATR أضيق من أن يبرر وقف خسارة.",
        "risk_stop": "الوقف داخل الضوضاء؛ إدارة المخاطر ترفض الصفقة.",
        "risk_ok": "المخاطرة مقبولة. ATR {atr}، بعد الوقف {stop}.",
        "tape_read": "مشاعر الشريط {score} (شراء {buy} / بيع {sell}).",
        "chain_none": "لا شريط سلسلة لهذا السوق؛ انتظار.",
        "chain_flow": "وكيل تدفق فوري {flow} من فرق الحجم لـ 24 شمعة — ليست بيانات سلسلة خام.",
        "oracle": "إجماع السرب {direction} من {confluence}/8 وكلاء. رصيد الشراء {bull} مقابل البيع {bear}.",
        "thin_history": "لا يكفي التاريخ لتشغيل السرب.",
    },
    "en": {
        "liq_bid": "Bid-side liquidity and resting support dominate the visible book.",
        "liq_ask": "Ask-side liquidity / resistance wall is absorbing demand.",
        "liq_flat": "Book is two-sided; no durable liquidity edge.",
        "pattern_read": "Structure read: {pattern}; 30-bar slope={slope}.",
        "quant_read": "EMA12/26 {ema}, MACD hist {hist}, RSI {rsi}, ATR {atr}.",
        "radar_quiet": "No anomaly vs 20-bar baseline.",
        "radar_alerts": "Alerts: {alerts}.",
        "news_empty": "No usable headlines in the news cache.",
        "news_tilt": "Headline tilt {score} across {hits} stories.",
        "risk_vol": "Volatility veto: ATR {atr} / bar range {range}.",
        "risk_dead": "Dead-range veto: ATR too thin to justify a stop.",
        "risk_stop": "Stop sits inside noise; Risk Management vetoes the setup.",
        "risk_ok": "Risk acceptable. ATR {atr}, stop distance {stop}.",
        "tape_read": "Tape sentiment {score} (buy {buy} / sell {sell}).",
        "chain_none": "No on-chain tape for this venue; waiting.",
        "chain_flow": "Spot flow proxy {flow} from 24-bar volume delta — not raw chain data.",
        "oracle": "Swarm consensus {direction} from {confluence}/8 agents. Bull {bull} vs bear {bear}.",
        "thin_history": "Not enough history to run the swarm.",
    },
    "fr": {
        "liq_bid": "La liquidité acheteuse et le support apparent dominent le carnet.",
        "liq_ask": "Un mur vendeur / de résistance absorbe la demande.",
        "liq_flat": "Carnet équilibré, sans avantage de liquidité durable.",
        "pattern_read": "Lecture de structure : {pattern} ; pente sur 30 barres = {slope}.",
        "quant_read": "EMA12/26 {ema}, hist. MACD {hist}, RSI {rsi}, ATR {atr}.",
        "radar_quiet": "Aucune anomalie face à la moyenne des 20 dernières barres.",
        "radar_alerts": "Alertes : {alerts}.",
        "news_empty": "Aucun titre exploitable dans le cache d’actualités.",
        "news_tilt": "Biais des titres {score} sur {hits} articles.",
        "risk_vol": "Veto volatilité : ATR {atr} / amplitude {range}.",
        "risk_dead": "Veto de range mort : ATR trop fin pour un stop.",
        "risk_stop": "Le stop est dans le bruit ; le risque refuse le setup.",
        "risk_ok": "Risque acceptable. ATR {atr}, distance du stop {stop}.",
        "tape_read": "Sentiment du flux {score} (achat {buy} / vente {sell}).",
        "chain_none": "Pas de flux on-chain pour ce marché ; en attente.",
        "chain_flow": "Proxy de flux spot {flow} sur 24 barres — pas de données chaîne brutes.",
        "oracle": "Consensus de l’essaim {direction} : {confluence}/8 agents. Achat {bull} vs vente {bear}.",
        "thin_history": "Historique insuffisant pour lancer l’essaim.",
    },
    "zh": {
        "liq_bid": "买盘流动性与可见支撑主导订单簿。",
        "liq_ask": "卖盘/阻力墙正在吸收需求。",
        "liq_flat": "订单簿双边均衡，没有持续的流动性优势。",
        "pattern_read": "结构解读：{pattern}；近30根斜率={slope}。",
        "quant_read": "EMA12/26 {ema}，MACD柱 {hist}，RSI {rsi}，ATR {atr}。",
        "radar_quiet": "相对近20根基线无明显异常。",
        "radar_alerts": "警报：{alerts}。",
        "news_empty": "新闻缓存中没有可用标题。",
        "news_tilt": "标题倾向 {score}，共 {hits} 条。",
        "risk_vol": "波动否决：ATR {atr} / K线波幅 {range}。",
        "risk_dead": "死区间否决：ATR过窄，无法设置止损。",
        "risk_stop": "止损落在噪音内；风控否决该设置。",
        "risk_ok": "风险可接受。ATR {atr}，止损距离 {stop}。",
        "tape_read": "盘口情绪 {score}（买 {buy} / 卖 {sell}）。",
        "chain_none": "该市场没有链上盘口；等待。",
        "chain_flow": "现货流量代理 {flow}，来自24根成交量差——不是原始链上数据。",
        "oracle": "蜂群共识 {direction}，{confluence}/8 个代理。多头 {bull} 对空头 {bear}。",
        "thin_history": "历史不足，无法运行蜂群。",
    },
    "ja": {
        "liq_bid": "買い側の流動性と支持が板を支配している。",
        "liq_ask": "売り壁／抵抗が需要を吸収している。",
        "liq_flat": "板は両面で、持続的な流動性優位はない。",
        "pattern_read": "構造：{pattern}。直近30本の傾き={slope}。",
        "quant_read": "EMA12/26は{ema}、MACDヒスト {hist}、RSI {rsi}、ATR {atr}。",
        "radar_quiet": "直近20本の基準に対する異常なし。",
        "radar_alerts": "警報：{alerts}。",
        "news_empty": "ニュースキャッシュに使える見出しがない。",
        "news_tilt": "見出しの傾き {score}（{hits}本）。",
        "risk_vol": "ボラティリティ拒否：ATR {atr} / 足幅 {range}。",
        "risk_dead": "デッドレンジ拒否：ATRが細すぎて損切りを置けない。",
        "risk_stop": "損切りがノイズ内。リスク管理が否決。",
        "risk_ok": "リスクは許容範囲。ATR {atr}、損切り距離 {stop}。",
        "tape_read": "テープ心理 {score}（買い {buy} / 売り {sell}）。",
        "chain_none": "この市場にオンチェーンテープなし。待機。",
        "chain_flow": "24本の出来高差からの現物流量代理 {flow}。生のチェーンデータではない。",
        "oracle": "群れの合意は{direction}（{confluence}/8）。買い {bull} 対 売り {bear}。",
        "thin_history": "履歴が足りず群れを実行できない。",
    },
    "es": {
        "liq_bid": "La liquidez compradora y el soporte visible dominan el libro.",
        "liq_ask": "El muro vendedor / de resistencia absorbe la demanda.",
        "liq_flat": "Libro equilibrado; sin ventaja de liquidez duradera.",
        "pattern_read": "Lectura de estructura: {pattern}; pendiente de 30 barras = {slope}.",
        "quant_read": "EMA12/26 {ema}, hist. MACD {hist}, RSI {rsi}, ATR {atr}.",
        "radar_quiet": "Sin anomalía frente a la media de 20 barras.",
        "radar_alerts": "Alertas: {alerts}.",
        "news_empty": "No hay titulares útiles en la caché de noticias.",
        "news_tilt": "Sesgo de titulares {score} en {hits} noticias.",
        "risk_vol": "Veto de volatilidad: ATR {atr} / rango {range}.",
        "risk_dead": "Veto de rango muerto: ATR demasiado fino para un stop.",
        "risk_stop": "El stop está en el ruido; riesgos rechaza el setup.",
        "risk_ok": "Riesgo aceptable. ATR {atr}, distancia del stop {stop}.",
        "tape_read": "Sentimiento de cinta {score} (compra {buy} / venta {sell}).",
        "chain_none": "No hay cinta on-chain en este mercado; en espera.",
        "chain_flow": "Proxy de flujo spot {flow} en 24 barras; no es dato on-chain crudo.",
        "oracle": "Consenso del enjambre {direction} de {confluence}/8 agentes. Compra {bull} vs venta {bear}.",
        "thin_history": "No hay historial suficiente para el enjambre.",
    },
    "de": {
        "liq_bid": "Kaufseitige Liquidität und sichtbare Unterstützung dominieren das Buch.",
        "liq_ask": "Verkaufswand / Widerstand absorbiert die Nachfrage.",
        "liq_flat": "Beidseitiges Buch; kein dauerhafter Liquiditätsvorteil.",
        "pattern_read": "Struktur: {pattern}; 30-Balken-Steigung = {slope}.",
        "quant_read": "EMA12/26 {ema}, MACD-Hist {hist}, RSI {rsi}, ATR {atr}.",
        "radar_quiet": "Keine Anomalie gegenüber dem 20-Balken-Mittel.",
        "radar_alerts": "Hinweise: {alerts}.",
        "news_empty": "Keine nutzbaren Schlagzeilen im Nachrichten-Cache.",
        "news_tilt": "Schlagzeilen-Neigung {score} über {hits} Meldungen.",
        "risk_vol": "Volatilitäts-Veto: ATR {atr} / Spanne {range}.",
        "risk_dead": "Totbereich-Veto: ATR zu dünn für einen Stop.",
        "risk_stop": "Stop liegt im Rauschen; Risikomanagement lehnt ab.",
        "risk_ok": "Risiko akzeptabel. ATR {atr}, Stop-Abstand {stop}.",
        "tape_read": "Tape-Stimmung {score} (Kauf {buy} / Verkauf {sell}).",
        "chain_none": "Kein On-Chain-Tape für diesen Markt; warten.",
        "chain_flow": "Spot-Flow-Proxy {flow} aus 24-Balken-Volumendelta — keine Roh-Chain-Daten.",
        "oracle": "Schwarm-Konsens {direction} von {confluence}/8 Agenten. Long {bull} vs Short {bear}.",
        "thin_history": "Zu wenig Historie für den Schwarm.",
    },
    "ko": {
        "liq_bid": "매수 유동성과 가시 지지가 호가창을 지배합니다.",
        "liq_ask": "매도벽/저항이 수요를 흡수하고 있습니다.",
        "liq_flat": "호가창이 양면 균형이며 지속적인 유동성 우위가 없습니다.",
        "pattern_read": "구조 해석: {pattern}. 최근 30봉 기울기={slope}.",
        "quant_read": "EMA12/26 {ema}, MACD 히스토그램 {hist}, RSI {rsi}, ATR {atr}.",
        "radar_quiet": "최근 20봉 기준 대비 이상 없음.",
        "radar_alerts": "경보: {alerts}.",
        "news_empty": "뉴스 캐시에 쓸 수 있는 제목이 없습니다.",
        "news_tilt": "헤드라인 기울기 {score} ({hits}건).",
        "risk_vol": "변동성 거부: ATR {atr} / 봉 범위 {range}.",
        "risk_dead": "데드 레인지 거부: ATR이 너무 얇아 손절을 둘 수 없음.",
        "risk_stop": "손절이 노이즈 안쪽입니다. 리스크가 설정을 거부합니다.",
        "risk_ok": "리스크 수용 가능. ATR {atr}, 손절 거리 {stop}.",
        "tape_read": "테이프 심리 {score} (매수 {buy} / 매도 {sell}).",
        "chain_none": "이 시장에는 온체인 테이프가 없습니다. 대기.",
        "chain_flow": "24봉 거래량 차이의 현물 흐름 대리 {flow}. 원본 체인 데이터 아님.",
        "oracle": "스웜 합의 {direction}, {confluence}/8 에이전트. 매수 {bull} 대 매도 {bear}.",
        "thin_history": "기록이 부족해 스웜을 실행할 수 없습니다.",
    },
    "ru": {
        "liq_bid": "Покупательская ликвидность и видимая поддержка доминируют в стакане.",
        "liq_ask": "Стена продаж / сопротивление поглощает спрос.",
        "liq_flat": "Стакан двусторонний; устойчивого преимущества ликвидности нет.",
        "pattern_read": "Структура: {pattern}; наклон 30 баров = {slope}.",
        "quant_read": "EMA12/26 {ema}, гист. MACD {hist}, RSI {rsi}, ATR {atr}.",
        "radar_quiet": "Нет аномалии относительно базы из 20 баров.",
        "radar_alerts": "Сигналы: {alerts}.",
        "news_empty": "В кэше новостей нет пригодных заголовков.",
        "news_tilt": "Наклон заголовков {score} по {hits} материалам.",
        "risk_vol": "Вето волатильности: ATR {atr} / диапазон {range}.",
        "risk_dead": "Вето мёртвого диапазона: ATR слишком тонкий для стопа.",
        "risk_stop": "Стоп внутри шума; риск-менеджмент отклоняет сетап.",
        "risk_ok": "Риск приемлем. ATR {atr}, дистанция стопа {stop}.",
        "tape_read": "Сентимент ленты {score} (покупка {buy} / продажа {sell}).",
        "chain_none": "Нет ончейн-ленты для этого рынка; ожидание.",
        "chain_flow": "Прокси спот-потока {flow} за 24 бара — не сырые ончейн-данные.",
        "oracle": "Консенсус роя {direction}: {confluence}/8 агентов. Лонг {bull} против шорт {bear}.",
        "thin_history": "Недостаточно истории для запуска роя.",
    },
}


def normalize_locale(locale: str) -> str:
    key = (locale or "ar").split("-")[0].lower()
    return key if key in SUPPORTED else "en"


def _word(locale: str, key: str) -> str:
    pack = _WORDS.get(locale) or _WORDS["en"]
    return pack.get(key) or (_WORDS["en"].get(key) or key)


def render_reason(code: str, params: dict[str, Any] | None, locale: str) -> str:
    loc = normalize_locale(locale)
    pack = _TEMPLATES.get(loc) or _TEMPLATES["en"]
    template = pack.get(code) or _TEMPLATES["en"].get(code)
    if not template:
        return ""
    data = dict(params or {})
    for key in ("direction", "ema", "pattern"):
        if key in data:
            data[key] = _word(loc, str(data[key]))
    alerts = data.get("alerts")
    if isinstance(alerts, list):
        data["alerts"] = " · ".join(_word(loc, str(item).split()[0]) + (f" {str(item).split(' ', 1)[1]}" if " " in str(item) else "") for item in alerts)
    return template.format(**data)


def localize_analysis(result: dict[str, Any], locale: str) -> dict[str, Any]:
    loc = normalize_locale(locale)
    for agent in result.get("agents") or []:
        text = render_reason(str(agent.get("reason_code") or ""), agent.get("reason_params") or {}, loc)
        if text:
            agent["reasoning"] = text
        agent["locale"] = loc
    text = render_reason(str(result.get("reason_code") or ""), result.get("reason_params") or {}, loc)
    if text:
        result["reasoning"] = text
    result["locale"] = loc
    return result
